// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtxHnJTMHatAIC_wB5Ahkw7sUQGRJ42Jg',
    appId: '1:22210022984:web:0199accf522122807bd27d',
    messagingSenderId: '22210022984',
    projectId: 'hasnain-zaidi',
    authDomain: 'hasnain-zaidi.firebaseapp.com',
    storageBucket: 'hasnain-zaidi.appspot.com',
    measurementId: 'G-Q7Q6K6CGXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgZH_kWm4N1kA4iZMi3kIehWbnmH9dz1Y',
    appId: '1:22210022984:android:7fc7af695ac1919c7bd27d',
    messagingSenderId: '22210022984',
    projectId: 'hasnain-zaidi',
    storageBucket: 'hasnain-zaidi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJAOwBC-c2mksR3uUQT77JmOPQTYjAKx4',
    appId: '1:22210022984:ios:3ccbf4d0f07c7ecf7bd27d',
    messagingSenderId: '22210022984',
    projectId: 'hasnain-zaidi',
    storageBucket: 'hasnain-zaidi.appspot.com',
    iosClientId: '22210022984-nst5iduu48lk72c0c8i8detslefspq9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.hello',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJAOwBC-c2mksR3uUQT77JmOPQTYjAKx4',
    appId: '1:22210022984:ios:3ccbf4d0f07c7ecf7bd27d',
    messagingSenderId: '22210022984',
    projectId: 'hasnain-zaidi',
    storageBucket: 'hasnain-zaidi.appspot.com',
    iosClientId: '22210022984-nst5iduu48lk72c0c8i8detslefspq9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.hello',
  );
}
